config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/about', to: 'static_pages#about'

  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :posts, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, :class_name => "User", :foreign_key => 'author_id'

  validates :author_id, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  attr_accessor :remember_token
  #before_create :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: {maximum: 255 }, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string
  def self.digest(string)
    #cost = BCrypt::Engine.cost
    #BCrypt::Password.create(string)
    Digest::SHA1.hexdigest(string)

  end

  # Returns a random token
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  #def remember
  #  self.update_attribute(:remember_digest, User.digest(remember_token))
  #end



  # Remembers a user in the database when they sign in
  def create_remember_digest
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :logged_in?


  # logs in and remembers user
  def log_in(user)
    #session[:user_id] = user.id
    user.create_remember_digest
    #cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token 
  end

  def current_user
    #if (user_id = session[:user_id])
    if (remember_token = cookies[:remember_token])
      @current_user ||= User.find_by(remember_digest: User.digest(remember_token))
    end
    #elsif (user_id = cookies.signed[:user_id])
    #  user = User.find_by(id: user_id)
    #  if user && user.authenticated?(:remember, cookies[:remember_token])
    #    log_in user
    #    @current_user = user
    #  end

    #@current_user ||= User.find_by(remember_digest: User.digest(cookies[:remember_token]))
  end

  #def current_user=(user)
  #  @current_user = User.find_by(id: user.id)
  #end

  def log_out
    #session.delete(:user_id)
    cookies.delete(:remember_token)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(author_id: current_user.id, content: params[:post][:content])
    if @post.save
      flash[:success] = "Posted"
      redirect_to posts_path 
    else
      flash[:danger] = "Error encountered when posting"
      render 'new'
    end
  end

  def index
    @posts = Post.all
  end

  # Before filters
  #
  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in"
      redirect_to login_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in(@user) 
      flash[:success] = "Welcome back #{@user.name}"
      redirect_to root_path
      debugger

    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new
    if @user.save
      p "User successfully created"
    else
      p "Error creating user"
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Anonymous Posts", root_path %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Posts", posts_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Log out", logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", new_user_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>

      <%= debug(params) if Rails.env.development? %>
    </div class="container">
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<h1>All Posts</h1>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.content %></td>
    <br>
    <% if logged_in? %>
      <td>- <%= post.user.name %></td>
    <% end %>
  </tr>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@post) do |f| %>

      <%= f.label :content %>
      <%= f.text_field :content %>

      <%= f.submit "Post" %>
    <% end %>
  </div>
</div>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Welcome</h1>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account" %>
    <% end %>
  </div>
</div>